---
fact_scan:
  author: "Will Tome"
  category: infrastructure
  name: "SERVER / Fact Scan"
  description: "scan facts for Linux and Windows systems"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: scan_facts.yml
  credential: "Workshop Credential"
  survey_enabled: false
  fact_caching_enabled: true
  project:
    name: "Ansible official awx-facts-playbooks project"
    description: "playbooks to support fact scanning in Ansible Tower"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/awx-facts-playbooks.git"
  workshop_type:
    - f5
    - rhel
    - windows
    - rhel_90
