---
- name: grab linux facts
  hosts: web
  gather_facts: true

- name: build developer report
  hosts: host1
  gather_facts: false

  vars:
    file_path: /var/www/html/report/index.html

  tasks:
    - name: use developer report
      include_role:
        name: "../roles/developer_report"
