---
developer_report:
  author: "Sean Cavanaugh"
  category: developer
  name: "DEVELOPER / Create Developer Report"
  description: Create HTML report using [Ansible facts](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variables-discovered-from-systems-facts)
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/developer/developer_report.yml"
  credential: "Workshop Credential"
  survey_enabled: false
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
    - demo
