---
- name: Application deployment
  hosts: "{{ _hosts | default('web') }}"
  gather_facts: false
  become: true

  tasks:
    - name: Make sure variable "application" is not empty
      ansible.builtin.assert:
        that:
          - "application != ''"

    - name: Print pre-installation message
      ansible.builtin.debug:
        msg: "This Ansible Playbook will install {{ application }}"

    - name: Install application
      ansible.builtin.dnf:
        name: "{{ application }}"
        allow_downgrade: true
      register: result

    - name: Print message if the application was already installed
      # noqa: no-handler
      ansible.builtin.debug:
        msg: "The application: {{ application }} was already installed"
      when: not result.changed | bool

...
