---
- name: install and configure insights agent on all specified nodes
  hosts: "{{ HOSTS | default('web') }}"
  roles:
    - role: RedHatInsights.insights-client
        vars:
          redhat_portal_username: "{{ insights_user }}"
          redhat_portal_password: "{{ insights_password }}"
          insights_display_name: "{{ inventory_hostname }}"
      when: ansible_os_family == 'RedHat'

    - name: print info to terminal window
      debug:
        msg: "Red Hat Insights is installed and configured for {{ inventory_hostname }}"
